package pipeline

import (
	"context"
	"time"

	"github.com/buchenberg/yaah/internal/types"
)

// Step is the mutable state passed through the pipeline at each iteration.
type Step struct {
	Messages      []types.Message
	Tools         []types.ToolDef
	Iteration     int
	MaxToolTurns  int // 0 = infinite; >0 = tools are stripped when Iteration >= MaxToolTurns
	MaxLoopCycles int // 0 = unlimited; >0 = hard loop exit when Iteration >= MaxLoopCycles
	Model         string
	SystemPrompt  string

	// SynthesizedResults holds tool-result messages generated by
	// middleware for tool calls removed before dispatch (approval
	// denials, inline-limit drops). Every tool_call_id on an assistant
	// message needs a result; executeToolPhase appends these ahead of
	// executed-call results so provider invariants hold. Middleware must
	// use this field rather than appending to Messages — PostModel output
	// is overwritten by the dispatch phase, which rebuilds Messages from
	// the Loop's local slice.
	SynthesizedResults []types.Message

	// InlineDropped counts calls dropped by inline_limit this turn, for
	// the dispatch phase's verbose OTel "inline.truncated" event.
	InlineDropped int
}

// ToolResult holds the outcome of a single tool execution for middleware inspection.
type ToolResult struct {
	Name     string
	Args     string
	Result   string
	Error    error
	Duration time.Duration
}

// Middleware intercepts the agent loop at well-defined points.
type Middleware interface {
	Name() string
	PrepareStep(ctx context.Context, step *Step) (*Step, error)
	PostModel(ctx context.Context, msg *types.Message, step *Step) (*Step, error)
	PostTool(ctx context.Context, results []ToolResult, step *Step) (*Step, error)
}
